services:
  mysql:
    container_name: prestashop_mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '8001:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  prestashop:
    container_name: prestashop_ps
    image: prestashop/prestashop:8.1-apache
    restart: always
    depends_on:
      - mysql
    ports:
      - '8000:80'
    environment:
      DB_SERVER: prestashop_mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_FOLDER_ADMIN: admin
      PS_FOLDER_INSTALL: install
    networks:
      - prestashop_network
    volumes:
      - ./prestaDocker:/var/www/html:delegated

networks:
  prestashop_network:

volumes:
  dbdata:
